/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#141317',
        'on-background': '#e6e1e7',
        surface: '#141317',
        'surface-dim': '#141317',
        'surface-bright': '#3b383d',
        'surface-container-lowest': '#0f0d12',
        'surface-container-low': '#1d1b20',
        'surface-container': '#211f24',
        'surface-container-high': '#2b292e',
        'surface-container-highest': '#363439',
        'on-surface': '#e6e1e7',
        'surface-variant': '#494550',
        'on-surface-variant': '#cbc4d1',
        'inverse-surface': '#e6e1e7',
        'inverse-on-surface': '#322f35',
        outline: '#948e9b',
        'outline-variant': '#494550',
        shadow: '#000000',
        scrim: '#000000',
        'surface-tint': '#d1bcff',
        primary: '#d1bcff',
        'on-primary': '#382367',
        'primary-container': '#624e94',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#675299',
        secondary: '#cdc1e4',
        'on-secondary': '#342c47',
        'secondary-container': '#413954',
        'on-secondary-container': '#d7cbee',
        tertiary: '#ffafd5',
        'on-tertiary': '#57183d',
        'tertiary-container': '#894269',
        'on-tertiary-container': '#ffffff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        salsa: ['Salsa', 'system-ui'],
        kalam: ['Kalam', 'cursive'],
      },
    },
  },
  plugins: [],
};
